//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Board_Table
    {
        public decimal Job_Id { get; set; }
        public string Job_Title { get; set; }
        public string Job_Desc { get; set; }
        public string Job_Type { get; set; }
        public string Job_Skill { get; set; }
        public string Job_Resp { get; set; }
        public string Job_Start_Date { get; set; }
        public string Job_End_Date { get; set; }
        public string Job_Created_By { get; set; }
        public string Job_Created_Date { get; set; }
        public string Job_Updated_By { get; set; }
        public string Job_Updated_Date { get; set; }
        public Nullable<decimal> Job_Status { get; set; }
    }
}
